### ISSUE TITLE
RegionCLIP detecions

### ISSUE THREAD

**Issue by Nathan-Li123** [balabooooo/AED#4]
Great work! I noticed that many scores in the RegionCLIP detection results are greater than 1 (as I understand it, scores should be between 0 and 1). What does this mean? Are they normal?

**Comment by balabooooo** [comment]
@Nathan-Li123 
Thank you for your question!

I also observed this during my experiments.
The computation of the output scores in RegionCLIP can be found in [here](https://github.com/microsoft/RegionCLIP/blob/4b8513b56e24827e3d6468e1f2105869f35c2d0b/detectron2/modeling/roi_heads/fast_rcnn.py#L711) and [here](https://github.com/microsoft/RegionCLIP/blob/4b8513b56e24827e3d6468e1f2105869f35c2d0b/detectron2/modeling/proposal_generator/rpn.py#L47):

```python
# where s is in [0, 1], and rpn_s is in [-inf, +inf]
scores = [(s * rpn_s[:, None]) ** 0.5 for s, rpn_s in zip(scores, rpn_scores)]
```

So it's normal.

**Comment by Nathan-Li123** [comment]
thanks
